//==============================================================================
// Project  : UGV1
// Module   : Controller
// File     : ControllerException.h
// Brief    : Exceptions generated by vehicle controller
//==============================================================================

#ifndef UGV1_CONTROLLEREXCEPTION_H
#define UGV1_CONTROLLEREXCEPTION_H

#include <core/Exception.h>
#include "controller_common.h"

namespace Ugv1
{
	/// \brief common base class for exceptions thrown by vehicle software
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API ControllerException : public Grape::Exception
	{
	public:
        ControllerException() throw() : Exception(0, "Unspecified Controller Exception") {}
		ControllerException(int code, const std::string& msg) throw() : Exception(code, msg.c_str()) {}
		ControllerException(const ControllerException& ve) throw() : Exception(ve) {}
		ControllerException& operator=(const ControllerException& other) throw() { Exception::operator=(other); return *this; }
	}; // ControllerException

	/// \brief Invalid message ID
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API InvalidMessageIdException : public ControllerException
	{
	public:
		InvalidMessageIdException() throw() : ControllerException(0, "Invalid message ID") {}
		InvalidMessageIdException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		InvalidMessageIdException(const InvalidMessageIdException& ve) throw() : ControllerException(ve) {}
		InvalidMessageIdException& operator=(const InvalidMessageIdException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // InvalidMessageIdException

	/// \brief Invalid message checksum
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API InvalidMessageChecksumException : public ControllerException
	{
	public:
		InvalidMessageChecksumException() throw() : ControllerException(0, "Invalid message checksum") {}
		InvalidMessageChecksumException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		InvalidMessageChecksumException(const InvalidMessageChecksumException& ve) throw() : ControllerException(ve) {}
		InvalidMessageChecksumException& operator=(const InvalidMessageChecksumException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // InvalidMessageChecksumException

	/// \brief Invalid message header
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API InvalidMessageHeaderException : public ControllerException
	{
	public:
		InvalidMessageHeaderException() throw() : ControllerException(0, "Invalid message header") {}
		InvalidMessageHeaderException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		InvalidMessageHeaderException(const InvalidMessageHeaderException& ve) throw() : ControllerException(ve) {}
		InvalidMessageHeaderException& operator=(const InvalidMessageHeaderException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // InvalidMessageHeaderException

	/// \brief Invalid message header
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API InvalidMessageLengthException : public ControllerException
	{
	public:
		InvalidMessageLengthException() throw() : ControllerException(0, "Invalid message length") {}
		InvalidMessageLengthException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		InvalidMessageLengthException(const InvalidMessageLengthException& ve) throw() : ControllerException(ve) {}
		InvalidMessageLengthException& operator=(const InvalidMessageLengthException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // InvalidMessageLengthException

	/// \brief IO operation didn't complete during assigned wait period
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API IoWaitException : public ControllerException
	{
	public:
		IoWaitException() throw() : ControllerException(0, "IO operation didn't complete within wait period") {}
		IoWaitException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		IoWaitException(const IoWaitException& ve) throw() : ControllerException(ve) {}
		IoWaitException& operator=(const IoWaitException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // IoWaitException
	
	/// \brief IO write operation failed
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API IoWriteException : public ControllerException
	{
	public:
		IoWriteException() throw() : ControllerException(0, "IO write operation failed") {}
		IoWriteException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		IoWriteException(const IoWriteException& ve) throw() : ControllerException(ve) {}
		IoWriteException& operator=(const IoWriteException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // IoWriteException

	/// \brief IO read operation failed
	/// \ingroup cont_exceptions
	class UGV1CONTROLLER_DLL_API IoReadException : public ControllerException
	{
	public:
		IoReadException() throw() : ControllerException(0, "IO read operation failed") {}
		IoReadException(int code, const std::string& msg) throw() : ControllerException(code, msg) {}
		IoReadException(const IoReadException& ve) throw() : ControllerException(ve) {}
		IoReadException& operator=(const IoReadException& other) throw() { ControllerException::operator=(other); return *this; }
	}; // IoReadException
	
} // Ugv1

#endif // UGV1_CONTROLLEREXCEPTION_H
